### ISSUE TITLE
cdnConfig内容迷惑

### ISSUE THREAD

**Issue by ghost** [75k/hexo-deployer-cos-enhanced#5]
```
  bucket: blog-1251123456  <--
  region: ap-shanghai
    cdnConfig:
      bucket: static-1251123456  <--
      region: ap-shanghai
```
为什么这两个bucket名称和地址要不一样？
现在腾讯搞成一个地方管理所有云产品的密钥，个人感觉cos 和cdn填相同的密钥就可以了
还有就是这个
```
    cdnConfig:
      folder: static-1251123456
```
仍然是没搞清这个是啥。如果这个是用来将文章中的链接更改为指向cos的话，把它放在cdnConfig下干啥？
